const {contextBridge, ipcRenderer, webUtils} = require('electron')

contextBridge.exposeInMainWorld('api', {
  getVersion: () => ipcRenderer.invoke('app:version'),
  openProject: () => ipcRenderer.invoke('app:open-project'),
  chooseMedia: () => ipcRenderer.invoke('dialog:media'),
  youTubeTitles: (ids) => ipcRenderer.invoke('youtube:titles', ids),
  chooseMediaFiles: () => ipcRenderer.invoke('dialog:media-files'),
  chooseSubtitle: () => ipcRenderer.invoke('dialog:subtitle'),
  downloadInfo: (filePath) => ipcRenderer.invoke('download:info', filePath),
  downloadOpen: (filePath, size) => ipcRenderer.invoke('download:open', filePath, size),
  downloadRead: (id, offset) => ipcRenderer.invoke('download:read', id, offset),
  downloadSave: (info) => ipcRenderer.invoke('download:save', info),
  downloadWrite: (id, offset, bytes) => ipcRenderer.invoke('download:write', id, offset, bytes),
  downloadFinish: (id) => ipcRenderer.invoke('download:finish', id),
  downloadCancel: (id) => ipcRenderer.invoke('download:cancel', id),
  pathForFile: (file) => webUtils.getPathForFile(file),
  probe: (filePath) => ipcRenderer.invoke('media:probe', filePath),
  availableFiles: (paths) => ipcRenderer.invoke('media:available-files', paths),
  readImage: (filePath) => ipcRenderer.invoke('media:image', filePath),
  startSession: (options) => ipcRenderer.invoke('session:start', options),
  pull: (sessionId) => ipcRenderer.invoke('session:pull', sessionId),
  stopSession: (sessionId) => ipcRenderer.invoke('session:stop', sessionId),
  subtitleCues: (options) => ipcRenderer.invoke('subtitle:cues', options),
  iceServers: () => ipcRenderer.invoke('net:ice-servers'),
  setPinned: (pinned) => ipcRenderer.invoke('window:pin', pinned),
  setZoom: (factor) => ipcRenderer.invoke('window:zoom', factor),
  onZoomStep: (handler) => ipcRenderer.on('zoom:step', (_event, direction) => handler(direction)),
  setInRoom: (inRoom) => ipcRenderer.send('app:in-room', inRoom),
  logEvents: (entries) => ipcRenderer.invoke('log:events', entries),
  saveDiagnostics: (options) => ipcRenderer.invoke('log:save', options),
  checkForUpdate: () => ipcRenderer.invoke('update:check'),
  openUpdate: (which) => ipcRenderer.invoke('update:open', which),
})
